version: '3'
services:
    jenkins:
        build:
            context: ./build/jenkins
            dockerfile: Dockerfile
        tty: true
        privileged: true
        ports:
            - '8080:8080'
            - '50000:50000'
        volumes:
            - './data/jenkins:/var/lib/jenkins'
    # other services