version: '3'
services:
    jenkins:
        build:
            context: .
            dockerfile: Dockerfile
        #restart: always
        tty: true
        ports:
            - '8080:8080'
            - '50000:50000'
        volumes:
            - './data/jenkins:/var/lib/jenkins'